version: build{build}

environment:
  matrix:
    - QT: C:\Qt\5.12\msvc2017_64
      GENERATOR: Visual Studio 15 2017 Win64
      PLATFORM: x64
    
clone_folder: c:\dev\qhexedit
clone_depth: 5

install:
    - dir C:\Qt
    - set PATH=%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;%PATH%
  
before_build:
    - dir "C:\Program Files (x86)"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
    - echo %path%
    - dir C:\Qt\5.12
    - dir C:\Qt\5.12\msvc2017_64
    - dir C:\Qt\5.12\msvc2017_64\bin
    - qmake --version
    - echo %PLATFORM%
    - cd c:\dev\qhexedit
    - md build
    - cd build
    - if "%PLATFORM%" EQU "x64" (qmake -r -spec win32-msvc CONFIG+=x86_64 CONFIG-=debug CONFIG+=release ..\example\qhexedit.pro)
    - if "%PLATFORM%" EQU "x86" (qmake -r -spec win32-msvc CONFIG+=Win32 CONFIG-=debug CONFIG+=release ..\example\qhexedit.pro)
  
build_script:
  - nmake
  - windeployqt.exe release\qhexedit.exe
  - makensis ..\deploy.nsi
 
artifacts:
  - path: build\QHexEdit.exe

deploy:
  description: 'Latest QHexEdit Release'
  provider: GitHub
  auth_token:
    secure: WEV9mRJC/pC2HFqJMXbLzEfBXAHu8aGDFIR8ARSip9n6jDJyCz3KstjSPM4VsgKc
  artifact: build\QHexEdit.exe
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
